---
version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_instance_2
    restart: always
    ports:
    - 9000:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
    - data-volume:/data
volumes:
  data-volume: null
